base_config:
  configs/base.yaml

# preprocessing
binarizer_cls: preprocessing.MIDIExtractionBinarizer
raw_data_dir: []
binary_data_dir: null
binarization_args:
  num_workers: 0
  skip_glide: true  # skip data with glide
  merge_rest: true  # merge continuous rest notes
  merge_slur: true  # merge slurs with the similar pitch
  round_midi: false  # round midi value
  slur_tolerance: 0.5  # maximum allowed value of pitch change of a slur to be merged

key_shift_factor: 8
key_shift_range: [-12, 12]
test_prefixes: []
units_encoder: mel  # contentvec768l12
units_encoder_ckpt: pretrained/contentvec/checkpoint_best_legacy_500.pt
pe: rmvpe
pe_ckpt: pretrained/rmvpe/model.pt

# global constants
midi_prob_deviation: 1.0
rest_threshold: 0.1

# neural networks
units_dim: 80  # 768
midi_num_bins: 128  # 256
model_cls: modules.model.Gmidi_conform.midi_conforms
midi_extractor_args:
  lay: 8
  dim: 512
  use_lay_skip: true
  kernel_size: 31
  conv_drop: 0.1
  ffn_latent_drop: 0.1
  ffn_out_drop: 0.1
  attention_drop: 0.1
  attention_heads: 8
  attention_heads_dim: 64

# training
task_cls: training.MIDIExtractionTask
optimizer_args:
  optimizer_cls: torch.optim.AdamW
  lr: 0.0001
  beta1: 0.9
  beta2: 0.98
  weight_decay: 0

lr_scheduler_args:
  scheduler_cls: lr_scheduler.scheduler.WarmupLR
  warmup_steps: 5000
  min_lr: 0.00001

max_batch_size: 8
max_batch_frames: 80000
num_valid_plots: 10
val_check_interval: 1000
num_ckpt_keep: 5
max_updates: 100000
permanent_ckpt_start: 60000
permanent_ckpt_interval: 8000
